In [5]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [9]:
zeros_arr=np.zeros((3,2))
print(zeros_arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [10]:
ones_arr=np.ones(3)
print(ones_arr)

[1. 1. 1.]


In [11]:
empty_arr=np.empty((3,2))
print(empty_arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [12]:
identy_matrix=np.eye(3)
print(identy_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
arr1=np.array([1,2,3],dtype=np.float64)
arr2=np.array([1,2,3],dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [17]:
arr=np.array([1,2,3])
print("Before converting:",arr,arr.dtype)
new_arr=arr.astype('f')
print("After converting:",new_arr,new_arr.dtype)

Before converting: [1 2 3] int64
After converting: [1. 2. 3.] float32


In [20]:
arr1=np.arange(10)
arr2=np.random.randn(10)
print("array 1\n",arr1,arr1.dtype)
print("array 2\n",arr2,arr2.dtype)
new_arr=arr.astype(arr2.dtype)
print("new array \n",new_arr,new_arr.dtype)

array 1
 [0 1 2 3 4 5 6 7 8 9] int64
array 2
 [-0.20658771  0.47560014  1.69728001 -0.54502195  1.62093628  0.48445832
  1.04281501 -0.32269843  0.95332017  2.29172752] float64
new array 
 [1. 2. 3.] float64


In [21]:
str_arr=np.array(['hello','world','numpy'])
print(str_arr)

['hello' 'world' 'numpy']


In [22]:
arr=np.arange(12)
newarr=arr.reshape(4,3)
print(newarr)
newarr=arr.reshape((4,3),order='f')
print("\n",newarr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [25]:
x=np.arange(10)
print(x)
x[5:]=2
print("\n After broadcasting1",x)
x[::2]=100
print("\n After broadcasting2",x)

[0 1 2 3 4 5 6 7 8 9]

 After broadcasting1 [0 1 2 3 4 2 2 2 2 2]

 After broadcasting2 [100   1 100   3 100   2 100   2 100   2]


In [26]:
a=np.arange(12).reshape(3,4)
print("a=\n",a)
b=a>4
print("b=\n",b)
print

a=
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b=
 [[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


<function print(*args, sep=' ', end='\n', file=None, flush=False)>

In [27]:
arr=np.arange(12).reshape((3,4))
print(arr)
print("transpose using.T")
print(arr.T)
print("transpose using the transpose() function")


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
transpose using.T
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
transpose using the transpose() function


In [29]:
arr1=np.transpose(arr,(1,0))
print(arr1)
arr2=np.transpose(arr,(0,1))
print(arr2)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [30]:
arr=np.arange(12).reshape((3,4))
print("Dot product of arr and arr2:")
print(np.dot(arr,arr.T))

Dot product of arr and arr2:
[[ 14  38  62]
 [ 38 126 214]
 [ 62 214 366]]


In [31]:
arr=np.arange(12).reshape((3,4))
print(arr)
print("swap axes 0 and 1:")
print(np.swapaxes(arr,0,1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
swap axes 0 and 1:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
